version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: churninsight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/churninsight
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - DS_SERVICE_URL=http://ml-service:8000
    depends_on:
      - postgres
      - ml-service

  frontend:
    build: ./churn-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"

volumes:
  postgres_data: